<?php

namespace app\admin\controller;

use think\Controller;

class Common extends Controller
{
    //初始化
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->isLogin();
    }

    //登录判断
    public function isLogin()
    {
        if(empty(session('admin_name'))){
            $this->error('还未登录,请先登录!','login/index');
        }
    }


}
